export default {
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  CHANGE_DIFFICULTY: 'CHANGE_DIFFICULTY',
  CHANGE_SEARCH: 'CHANGE_SEARCH',
  FETCH_COURSES: 'FETCH_COURSES',
  CHANGE_COURSES: 'CHANGE_COURSES',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  CHANGE_PAGE_SIZE: 'CHANGE_PAGE_SIZE',
  CHANGE_PAGE_NUMBER: 'CHANGE_PAGE_NUMBER',
  CHANGE_PAGE_TOTAL: 'CHANGE_PAGE_TOTAL',
}